### ISSUE TITLE
性能提升不上去 兄弟 有没有更好的方式来处理同步

### ISSUE THREAD

**Issue by kotlin711** [golang-infrastructure/go-stack#1]
go sync 会导致cpu上下文切换 影响性能

**Comment by songzhibin97** [comment]
可以说一下场景吗，什么情况下使用sync成为瓶颈的情况

**Comment by kotlin711** [comment]
我在做一个比特币地址生成的程序

代码大概是这样的
···
func generateNewKeys() {
	for {
		for f := 0; f < fileLine; f++ {

			go generateNewKey()
		}
		saveDataSync()
	}
}
···
generateNewKey() 这个函数会生成比特币的私钥和公钥
然后我用SyncArrayStack 把生成地址和私钥 push进去

saveDataSync() 这个函数是将SyncArrayStack  里面的数据取出 然后保存在txt 文件中


我经过测试 在低配置电脑发现不了问题


当我切换为服务器的时候 发现CPU 并没有跑满 
我使用 不同步的ArrayStack可以跑慢

服务器配置
![image](https://user-images.githubusercontent.com/86459514/204437824-c205d066-dfd8-4b74-984c-714ca00c2f00.png)

本地电脑配置
![image](https://user-images.githubusercontent.com/86459514/204437945-d0e6b5b2-d5b6-46a4-bf95-9fa845682ed3.png)

**Comment by songzhibin97** [comment]
提供一下pprof文件

**Comment by kotlin711** [comment]
close
